implemented method GetRestaurants, getMenu which runns (every 60sec) …
Igor-Koniukhov/fastcat pull request #5
Opened 2021-09-02 16:00 UTC by Igor-Koniukhov

Implemented method GetRestaurants, getMenu which runns (every 60sec) with runUpdate function in main-func.  Location - helpers/get_menu.go.

2021-09-03 06:50 UTC, pechenini requested changes

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +package helpers
почему логика обновления ресторанов находятся в helppers? для нее желательно выделить отдельный пакет

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +func (r RestMenuRepository) GetRestaurants() {
Название метода GetRestaurants и кажется, что этот метод должен что-то возвращать, надо переименовать

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +	tx.Exec("DELETE FROM " + TabSuppliers)
а если у нас в бд уже были заказы из этого ресторана? мы же тогда удалим данный, которые нужны для отображения истории, поэтому удалять не стоит, нужно делать soft delete

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +		r.getMenu(restaurant.Id, tx)
где асинхронность?

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +func (r RestMenuRepository) getMenu(id int, tx *sql.Tx) {
опять же getMenu вводит в заблуждение, кажется, что метод должен что-то возвращать, надо преименовать

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +func responseConnection(url string) (response []byte) {
почему метод называется responseConnection, если он возвращает просто слайс байт и почему он в этом пакете?

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +var ctx context.Context
обычно ctx не добавляют как глобальную  переменную пакета, ее передают в методы во время вызова

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +type RestMenuRepository struct {
репозиторий ->  это штука для получения или работы с объектами из бд, не для парсинга сервисов и потом созхранения в бд

2021-09-03 06:50 UTC, pechenini commented on helpers/get_menu.go
> +	stmtSQL, err := tx.Prepare("INSERT suppliers SET id=?, name=?")
id не сетят, он автоматом генерируется

2021-09-06 06:40 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +package helpers
создал отдельный пакет internal/parser

2021-09-06 06:42 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +func (r RestMenuRepository) GetRestaurants() {
Название метода и его логика изменены

2021-09-06 06:43 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +	tx.Exec("DELETE FROM " + TabSuppliers)
Реализован метод с soft delete.

2021-09-06 06:44 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +func (r RestMenuRepository) getMenu(id int, tx *sql.Tx) {
Изменено название и логика метода.

2021-09-06 06:50 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +type RestMenuRepository struct {
Изменено название

2021-09-06 06:50 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +	stmtSQL, err := tx.Prepare("INSERT suppliers SET id=?, name=?")
Исправлено

2021-09-06 06:50 UTC, merged

2021-09-06 07:07 UTC, Igor-Koniukhov commented on helpers/get_menu.go
> +func responseConnection(url string) (response []byte) {
Метод в статусе функции перенесен в пакет drivers